name: linked_timers
description: "Timers Who Are Linked"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^8.2.0
  stop_watch_timer: ^3.2.2
  percent_indicator: ^4.2.5
  riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  uuid: ^4.5.1
  flutter_riverpod: ^3.0.0-dev.15
  flutter_layout_grid: ^2.0.8
  scrollable_positioned_list: ^0.3.8
  animated_list_plus: ^0.5.2
  clickable_list_wheel_view: ^0.2.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.2.1
  flutter_background: ^1.3.0+1
  contextmenu: ^3.0.0
  flutter_context_menu: ^0.2.4
  alarm: ^5.1.4
  permission_handler: ^12.0.0+1
  scroll_to_hide: ^2.2.1
  riverpod_lint: ^3.0.0-dev.16
  flutter_launcher_icons: ^0.14.4
  layout_grids: ^0.2.0
  flutter_reorderable_list: ^1.3.1
  fluttertoast: ^8.2.12
  flutter_slidable: ^4.0.0
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_generator: ^3.0.0-dev.15
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/alarms/alarm-default-short.mp3
    - assets/images/overhead.png
    - assets/images/icon/icon-background.png
    - assets/images/icon/icon-alarm.png
    - assets/images/icon/icon-notification.png
    - assets/images/icon/icon-paused.png
    - assets/images/icon/icon-play.png
    - assets/images/icon/icon-transparent.png
